name: Make release

permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Prepare Module ZIP
        run: |
          make

      - name: Upload CI artifact
        uses: actions/upload-artifact@v7
        with:
          path: "out/*.zip"
          archive: false

      - name: Prepare remote
        if: github.event_name != 'pull_request'
        env:
         GH_TOKEN: ${{ github.token }}
        run: |
          git clone "https://github.com/${{ github.repository }}" --depth=1 -b "remote" remote
          rm -rf remote/*.zip || true
          make MODULE_ZIP="HotInstall-Standalone"
          mv "out/HotInstall-Standalone.zip" remote/

          latest_tag=$(git describe --tags --abbrev=0 || echo "v1")
          latest_code=$(git rev-list HEAD --count 2>/dev/null || echo 1)

          cd remote/
          sed -Ei "s/\"version\": \".*?\"/\"version\": \"${latest_tag} (${latest_code})\"/" update.json
          sed -Ei "s/\"versionCode\": .*?,/\"versionCode\": ${latest_code},/" update.json
          sed -Ei 's/"zipUrl": ".*?"/"zipUrl": "https:\/\/raw.githubusercontent.com\/TheSillyOk\/HotInstall-Standalone\/refs\/heads\/remote\/HotInstall-Standalone.zip"/' update.json

          gh auth setup-git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .

          if [ '${{ github.ref_type }}' == 'tag' ]; then
            git commit -m "CI ${{ github.run_number }} - ${{ github.ref_name }}"
          else
            git commit -m "CI ${{ github.run_number }}"
          fi

          git push origin remote
          latest_remote=$(git rev-parse --verify HEAD 2>/dev/null)
          echo "latest_remote=${latest_remote}" >> $GITHUB_ENV

      - name: Upload to release
        if: github.event_name != 'pull_request' && github.ref_type == 'tag'
        env:
         GH_TOKEN: ${{ github.token }}
        run: |
          cd module/
          sed -Ei 's/(updateJson=).*json/\1https:\/\/github.com\/TheSillyOk\/HotInstall-Standalone\/releases\/latest\/download\/update.json/' module.prop
          cd ..
          make clean && make

          cd remote/
          gh release upload "${{ github.ref_name }}" "../out/*.zip"
          sed -Ei 's/"zipUrl": ".*?"/"zipUrl": "https:\/\/github.com\/TheSillyOk\/HotInstall-Standalone\/raw\/${{ env.latest_remote }}\/HotInstall-Standalone.zip"/' update.json
          sed -Ei 's/"changelog": ".*?"/"changelog": "https:\/\/github.com\/TheSillyOk\/HotInstall-Standalone\/raw\/${{ env.latest_remote }}\/changelog.md"/' update.json
          gh release upload "${{ github.ref_name }}" "update.json"
